// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: confa/extensions.proto

package confa

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_confa_extensions_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         33301,
		Name:          "skip_auth",
		Tag:           "varint,33301,opt,name=skip_auth",
		Filename:      "confa/extensions.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional bool skip_auth = 33301;
	E_SkipAuth = &file_confa_extensions_proto_extTypes[0]
)

var File_confa_extensions_proto protoreflect.FileDescriptor

const file_confa_extensions_proto_rawDesc = "" +
	"\n" +
	"\x16confa/extensions.proto\x1a google/protobuf/descriptor.proto:=\n" +
	"\tskip_auth\x12\x1e.google.protobuf.MethodOptions\x18\x95\x84\x02 \x01(\bR\bskipAuthB?B\x0fExtensionsProtoP\x01Z*github.com/confa-chat/node/src/proto/confab\x06proto3"

var file_confa_extensions_proto_goTypes = []any{
	(*descriptorpb.MethodOptions)(nil), // 0: google.protobuf.MethodOptions
}
var file_confa_extensions_proto_depIdxs = []int32{
	0, // 0: skip_auth:extendee -> google.protobuf.MethodOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_confa_extensions_proto_init() }
func file_confa_extensions_proto_init() {
	if File_confa_extensions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_confa_extensions_proto_rawDesc), len(file_confa_extensions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_confa_extensions_proto_goTypes,
		DependencyIndexes: file_confa_extensions_proto_depIdxs,
		ExtensionInfos:    file_confa_extensions_proto_extTypes,
	}.Build()
	File_confa_extensions_proto = out.File
	file_confa_extensions_proto_goTypes = nil
	file_confa_extensions_proto_depIdxs = nil
}
