// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: confa/chat/v1/service.proto

package chatv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TextChannelRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextChannelRef) Reset() {
	*x = TextChannelRef{}
	mi := &file_confa_chat_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextChannelRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextChannelRef) ProtoMessage() {}

func (x *TextChannelRef) ProtoReflect() protoreflect.Message {
	mi := &file_confa_chat_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextChannelRef.ProtoReflect.Descriptor instead.
func (*TextChannelRef) Descriptor() ([]byte, []int) {
	return file_confa_chat_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *TextChannelRef) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *TextChannelRef) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       *TextChannelRef        `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	AttachmentIds []string               `protobuf:"bytes,3,rep,name=attachment_ids,json=attachmentIds,proto3" json:"attachment_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_confa_chat_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_confa_chat_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_confa_chat_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageRequest) GetChannel() *TextChannelRef {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendMessageRequest) GetAttachmentIds() []string {
	if x != nil {
		return x.AttachmentIds
	}
	return nil
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_confa_chat_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_confa_chat_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_confa_chat_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *SendMessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SenderId      string                 `protobuf:"bytes,4,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Attachments   []*Attachment          `protobuf:"bytes,7,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_confa_chat_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_confa_chat_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_confa_chat_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *Message) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Message) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Message) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

type Attachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttachmentId  string                 `protobuf:"bytes,1,opt,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_confa_chat_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_confa_chat_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_confa_chat_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *Attachment) GetAttachmentId() string {
	if x != nil {
		return x.AttachmentId
	}
	return ""
}

func (x *Attachment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Attachment) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetMessageHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       *TextChannelRef        `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	From          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageHistoryRequest) Reset() {
	*x = GetMessageHistoryRequest{}
	mi := &file_confa_chat_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageHistoryRequest) ProtoMessage() {}

func (x *GetMessageHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_confa_chat_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetMessageHistoryRequest) Descriptor() ([]byte, []int) {
	return file_confa_chat_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetMessageHistoryRequest) GetChannel() *TextChannelRef {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *GetMessageHistoryRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *GetMessageHistoryRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetMessageHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageHistoryResponse) Reset() {
	*x = GetMessageHistoryResponse{}
	mi := &file_confa_chat_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageHistoryResponse) ProtoMessage() {}

func (x *GetMessageHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_confa_chat_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetMessageHistoryResponse) Descriptor() ([]byte, []int) {
	return file_confa_chat_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetMessageHistoryResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type GetMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       *TextChannelRef        `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageRequest) Reset() {
	*x = GetMessageRequest{}
	mi := &file_confa_chat_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageRequest) ProtoMessage() {}

func (x *GetMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_confa_chat_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageRequest.ProtoReflect.Descriptor instead.
func (*GetMessageRequest) Descriptor() ([]byte, []int) {
	return file_confa_chat_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetMessageRequest) GetChannel() *TextChannelRef {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *GetMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type GetMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageResponse) Reset() {
	*x = GetMessageResponse{}
	mi := &file_confa_chat_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageResponse) ProtoMessage() {}

func (x *GetMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_confa_chat_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageResponse.ProtoReflect.Descriptor instead.
func (*GetMessageResponse) Descriptor() ([]byte, []int) {
	return file_confa_chat_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetMessageResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type StreamNewMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       *TextChannelRef        `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamNewMessagesRequest) Reset() {
	*x = StreamNewMessagesRequest{}
	mi := &file_confa_chat_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamNewMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamNewMessagesRequest) ProtoMessage() {}

func (x *StreamNewMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_confa_chat_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamNewMessagesRequest.ProtoReflect.Descriptor instead.
func (*StreamNewMessagesRequest) Descriptor() ([]byte, []int) {
	return file_confa_chat_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *StreamNewMessagesRequest) GetChannel() *TextChannelRef {
	if x != nil {
		return x.Channel
	}
	return nil
}

type StreamNewMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamNewMessagesResponse) Reset() {
	*x = StreamNewMessagesResponse{}
	mi := &file_confa_chat_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamNewMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamNewMessagesResponse) ProtoMessage() {}

func (x *StreamNewMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_confa_chat_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamNewMessagesResponse.ProtoReflect.Descriptor instead.
func (*StreamNewMessagesResponse) Descriptor() ([]byte, []int) {
	return file_confa_chat_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *StreamNewMessagesResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type UploadAttachmentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*UploadAttachmentRequest_Info
	//	*UploadAttachmentRequest_Data
	Payload       isUploadAttachmentRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAttachmentRequest) Reset() {
	*x = UploadAttachmentRequest{}
	mi := &file_confa_chat_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAttachmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAttachmentRequest) ProtoMessage() {}

func (x *UploadAttachmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_confa_chat_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAttachmentRequest.ProtoReflect.Descriptor instead.
func (*UploadAttachmentRequest) Descriptor() ([]byte, []int) {
	return file_confa_chat_v1_service_proto_rawDescGZIP(), []int{11}
}

func (x *UploadAttachmentRequest) GetPayload() isUploadAttachmentRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UploadAttachmentRequest) GetInfo() *AttachmentUploadInfo {
	if x != nil {
		if x, ok := x.Payload.(*UploadAttachmentRequest_Info); ok {
			return x.Info
		}
	}
	return nil
}

func (x *UploadAttachmentRequest) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*UploadAttachmentRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isUploadAttachmentRequest_Payload interface {
	isUploadAttachmentRequest_Payload()
}

type UploadAttachmentRequest_Info struct {
	Info *AttachmentUploadInfo `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type UploadAttachmentRequest_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*UploadAttachmentRequest_Info) isUploadAttachmentRequest_Payload() {}

func (*UploadAttachmentRequest_Data) isUploadAttachmentRequest_Payload() {}

type AttachmentUploadInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachmentUploadInfo) Reset() {
	*x = AttachmentUploadInfo{}
	mi := &file_confa_chat_v1_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachmentUploadInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachmentUploadInfo) ProtoMessage() {}

func (x *AttachmentUploadInfo) ProtoReflect() protoreflect.Message {
	mi := &file_confa_chat_v1_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachmentUploadInfo.ProtoReflect.Descriptor instead.
func (*AttachmentUploadInfo) Descriptor() ([]byte, []int) {
	return file_confa_chat_v1_service_proto_rawDescGZIP(), []int{12}
}

func (x *AttachmentUploadInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UploadAttachmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttachmentId  string                 `protobuf:"bytes,1,opt,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAttachmentResponse) Reset() {
	*x = UploadAttachmentResponse{}
	mi := &file_confa_chat_v1_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAttachmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAttachmentResponse) ProtoMessage() {}

func (x *UploadAttachmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_confa_chat_v1_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAttachmentResponse.ProtoReflect.Descriptor instead.
func (*UploadAttachmentResponse) Descriptor() ([]byte, []int) {
	return file_confa_chat_v1_service_proto_rawDescGZIP(), []int{13}
}

func (x *UploadAttachmentResponse) GetAttachmentId() string {
	if x != nil {
		return x.AttachmentId
	}
	return ""
}

var File_confa_chat_v1_service_proto protoreflect.FileDescriptor

const file_confa_chat_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1bconfa/chat/v1/service.proto\x12\rconfa.chat.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"L\n" +
	"\x0eTextChannelRef\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\"\x8e\x01\n" +
	"\x12SendMessageRequest\x127\n" +
	"\achannel\x18\x01 \x01(\v2\x1d.confa.chat.v1.TextChannelRefR\achannel\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12%\n" +
	"\x0eattachment_ids\x18\x03 \x03(\tR\rattachmentIds\"4\n" +
	"\x13SendMessageResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"\xd6\x01\n" +
	"\aMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tsender_id\x18\x04 \x01(\tR\bsenderId\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12;\n" +
	"\vattachments\x18\a \x03(\v2\x19.confa.chat.v1.AttachmentR\vattachments\"W\n" +
	"\n" +
	"Attachment\x12#\n" +
	"\rattachment_id\x18\x01 \x01(\tR\fattachmentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"\x99\x01\n" +
	"\x18GetMessageHistoryRequest\x127\n" +
	"\achannel\x18\x01 \x01(\v2\x1d.confa.chat.v1.TextChannelRefR\achannel\x12.\n" +
	"\x04from\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"O\n" +
	"\x19GetMessageHistoryResponse\x122\n" +
	"\bmessages\x18\x01 \x03(\v2\x16.confa.chat.v1.MessageR\bmessages\"k\n" +
	"\x11GetMessageRequest\x127\n" +
	"\achannel\x18\x01 \x01(\v2\x1d.confa.chat.v1.TextChannelRefR\achannel\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\"F\n" +
	"\x12GetMessageResponse\x120\n" +
	"\amessage\x18\x01 \x01(\v2\x16.confa.chat.v1.MessageR\amessage\"S\n" +
	"\x18StreamNewMessagesRequest\x127\n" +
	"\achannel\x18\x01 \x01(\v2\x1d.confa.chat.v1.TextChannelRefR\achannel\":\n" +
	"\x19StreamNewMessagesResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"u\n" +
	"\x17UploadAttachmentRequest\x129\n" +
	"\x04info\x18\x01 \x01(\v2#.confa.chat.v1.AttachmentUploadInfoH\x00R\x04info\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\apayload\"*\n" +
	"\x14AttachmentUploadInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"?\n" +
	"\x18UploadAttachmentResponse\x12#\n" +
	"\rattachment_id\x18\x01 \x01(\tR\fattachmentId2\xf9\x03\n" +
	"\vChatService\x12V\n" +
	"\vSendMessage\x12!.confa.chat.v1.SendMessageRequest\x1a\".confa.chat.v1.SendMessageResponse\"\x00\x12h\n" +
	"\x11GetMessageHistory\x12'.confa.chat.v1.GetMessageHistoryRequest\x1a(.confa.chat.v1.GetMessageHistoryResponse\"\x00\x12S\n" +
	"\n" +
	"GetMessage\x12 .confa.chat.v1.GetMessageRequest\x1a!.confa.chat.v1.GetMessageResponse\"\x00\x12j\n" +
	"\x11StreamNewMessages\x12'.confa.chat.v1.StreamNewMessagesRequest\x1a(.confa.chat.v1.StreamNewMessagesResponse\"\x000\x01\x12g\n" +
	"\x10UploadAttachment\x12&.confa.chat.v1.UploadAttachmentRequest\x1a'.confa.chat.v1.UploadAttachmentResponse\"\x00(\x01B\xb1\x01\n" +
	"\x11com.confa.chat.v1B\fServiceProtoP\x01Z8github.com/confa-chat/node/src/proto/confa/chat/v1;chatv1\xa2\x02\x03KCX\xaa\x02\rConfa.Chat.V1\xca\x02\rConfa\\Chat\\V1\xe2\x02\x19Confa\\Chat\\V1\\GPBMetadata\xea\x02\x0fConfa::Chat::V1b\x06proto3"

var (
	file_confa_chat_v1_service_proto_rawDescOnce sync.Once
	file_confa_chat_v1_service_proto_rawDescData []byte
)

func file_confa_chat_v1_service_proto_rawDescGZIP() []byte {
	file_confa_chat_v1_service_proto_rawDescOnce.Do(func() {
		file_confa_chat_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_confa_chat_v1_service_proto_rawDesc), len(file_confa_chat_v1_service_proto_rawDesc)))
	})
	return file_confa_chat_v1_service_proto_rawDescData
}

var file_confa_chat_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_confa_chat_v1_service_proto_goTypes = []any{
	(*TextChannelRef)(nil),            // 0: confa.chat.v1.TextChannelRef
	(*SendMessageRequest)(nil),        // 1: confa.chat.v1.SendMessageRequest
	(*SendMessageResponse)(nil),       // 2: confa.chat.v1.SendMessageResponse
	(*Message)(nil),                   // 3: confa.chat.v1.Message
	(*Attachment)(nil),                // 4: confa.chat.v1.Attachment
	(*GetMessageHistoryRequest)(nil),  // 5: confa.chat.v1.GetMessageHistoryRequest
	(*GetMessageHistoryResponse)(nil), // 6: confa.chat.v1.GetMessageHistoryResponse
	(*GetMessageRequest)(nil),         // 7: confa.chat.v1.GetMessageRequest
	(*GetMessageResponse)(nil),        // 8: confa.chat.v1.GetMessageResponse
	(*StreamNewMessagesRequest)(nil),  // 9: confa.chat.v1.StreamNewMessagesRequest
	(*StreamNewMessagesResponse)(nil), // 10: confa.chat.v1.StreamNewMessagesResponse
	(*UploadAttachmentRequest)(nil),   // 11: confa.chat.v1.UploadAttachmentRequest
	(*AttachmentUploadInfo)(nil),      // 12: confa.chat.v1.AttachmentUploadInfo
	(*UploadAttachmentResponse)(nil),  // 13: confa.chat.v1.UploadAttachmentResponse
	(*timestamppb.Timestamp)(nil),     // 14: google.protobuf.Timestamp
}
var file_confa_chat_v1_service_proto_depIdxs = []int32{
	0,  // 0: confa.chat.v1.SendMessageRequest.channel:type_name -> confa.chat.v1.TextChannelRef
	14, // 1: confa.chat.v1.Message.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 2: confa.chat.v1.Message.attachments:type_name -> confa.chat.v1.Attachment
	0,  // 3: confa.chat.v1.GetMessageHistoryRequest.channel:type_name -> confa.chat.v1.TextChannelRef
	14, // 4: confa.chat.v1.GetMessageHistoryRequest.from:type_name -> google.protobuf.Timestamp
	3,  // 5: confa.chat.v1.GetMessageHistoryResponse.messages:type_name -> confa.chat.v1.Message
	0,  // 6: confa.chat.v1.GetMessageRequest.channel:type_name -> confa.chat.v1.TextChannelRef
	3,  // 7: confa.chat.v1.GetMessageResponse.message:type_name -> confa.chat.v1.Message
	0,  // 8: confa.chat.v1.StreamNewMessagesRequest.channel:type_name -> confa.chat.v1.TextChannelRef
	12, // 9: confa.chat.v1.UploadAttachmentRequest.info:type_name -> confa.chat.v1.AttachmentUploadInfo
	1,  // 10: confa.chat.v1.ChatService.SendMessage:input_type -> confa.chat.v1.SendMessageRequest
	5,  // 11: confa.chat.v1.ChatService.GetMessageHistory:input_type -> confa.chat.v1.GetMessageHistoryRequest
	7,  // 12: confa.chat.v1.ChatService.GetMessage:input_type -> confa.chat.v1.GetMessageRequest
	9,  // 13: confa.chat.v1.ChatService.StreamNewMessages:input_type -> confa.chat.v1.StreamNewMessagesRequest
	11, // 14: confa.chat.v1.ChatService.UploadAttachment:input_type -> confa.chat.v1.UploadAttachmentRequest
	2,  // 15: confa.chat.v1.ChatService.SendMessage:output_type -> confa.chat.v1.SendMessageResponse
	6,  // 16: confa.chat.v1.ChatService.GetMessageHistory:output_type -> confa.chat.v1.GetMessageHistoryResponse
	8,  // 17: confa.chat.v1.ChatService.GetMessage:output_type -> confa.chat.v1.GetMessageResponse
	10, // 18: confa.chat.v1.ChatService.StreamNewMessages:output_type -> confa.chat.v1.StreamNewMessagesResponse
	13, // 19: confa.chat.v1.ChatService.UploadAttachment:output_type -> confa.chat.v1.UploadAttachmentResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_confa_chat_v1_service_proto_init() }
func file_confa_chat_v1_service_proto_init() {
	if File_confa_chat_v1_service_proto != nil {
		return
	}
	file_confa_chat_v1_service_proto_msgTypes[11].OneofWrappers = []any{
		(*UploadAttachmentRequest_Info)(nil),
		(*UploadAttachmentRequest_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_confa_chat_v1_service_proto_rawDesc), len(file_confa_chat_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_confa_chat_v1_service_proto_goTypes,
		DependencyIndexes: file_confa_chat_v1_service_proto_depIdxs,
		MessageInfos:      file_confa_chat_v1_service_proto_msgTypes,
	}.Build()
	File_confa_chat_v1_service_proto = out.File
	file_confa_chat_v1_service_proto_goTypes = nil
	file_confa_chat_v1_service_proto_depIdxs = nil
}
