// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: confa/node/v1/service.proto

package nodev1

import (
	_ "github.com/confa-chat/node/src/proto/confa"
	v1 "github.com/confa-chat/node/src/proto/confa/user/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SupportedClientVersionsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CurrentVersion string                 `protobuf:"bytes,1,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SupportedClientVersionsRequest) Reset() {
	*x = SupportedClientVersionsRequest{}
	mi := &file_confa_node_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportedClientVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportedClientVersionsRequest) ProtoMessage() {}

func (x *SupportedClientVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_confa_node_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportedClientVersionsRequest.ProtoReflect.Descriptor instead.
func (*SupportedClientVersionsRequest) Descriptor() ([]byte, []int) {
	return file_confa_node_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *SupportedClientVersionsRequest) GetCurrentVersion() string {
	if x != nil {
		return x.CurrentVersion
	}
	return ""
}

type SupportedClientVersionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Supported     bool                   `protobuf:"varint,1,opt,name=supported,proto3" json:"supported,omitempty"`
	MinVersion    string                 `protobuf:"bytes,2,opt,name=min_version,json=minVersion,proto3" json:"min_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupportedClientVersionsResponse) Reset() {
	*x = SupportedClientVersionsResponse{}
	mi := &file_confa_node_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportedClientVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportedClientVersionsResponse) ProtoMessage() {}

func (x *SupportedClientVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_confa_node_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportedClientVersionsResponse.ProtoReflect.Descriptor instead.
func (*SupportedClientVersionsResponse) Descriptor() ([]byte, []int) {
	return file_confa_node_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *SupportedClientVersionsResponse) GetSupported() bool {
	if x != nil {
		return x.Supported
	}
	return false
}

func (x *SupportedClientVersionsResponse) GetMinVersion() string {
	if x != nil {
		return x.MinVersion
	}
	return ""
}

type ListServersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServersRequest) Reset() {
	*x = ListServersRequest{}
	mi := &file_confa_node_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServersRequest) ProtoMessage() {}

func (x *ListServersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_confa_node_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServersRequest.ProtoReflect.Descriptor instead.
func (*ListServersRequest) Descriptor() ([]byte, []int) {
	return file_confa_node_v1_service_proto_rawDescGZIP(), []int{2}
}

type ListServersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerIds     []string               `protobuf:"bytes,1,rep,name=server_ids,json=serverIds,proto3" json:"server_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServersResponse) Reset() {
	*x = ListServersResponse{}
	mi := &file_confa_node_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServersResponse) ProtoMessage() {}

func (x *ListServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_confa_node_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServersResponse.ProtoReflect.Descriptor instead.
func (*ListServersResponse) Descriptor() ([]byte, []int) {
	return file_confa_node_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListServersResponse) GetServerIds() []string {
	if x != nil {
		return x.ServerIds
	}
	return nil
}

type ListVoiceRelaysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVoiceRelaysRequest) Reset() {
	*x = ListVoiceRelaysRequest{}
	mi := &file_confa_node_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVoiceRelaysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVoiceRelaysRequest) ProtoMessage() {}

func (x *ListVoiceRelaysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_confa_node_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVoiceRelaysRequest.ProtoReflect.Descriptor instead.
func (*ListVoiceRelaysRequest) Descriptor() ([]byte, []int) {
	return file_confa_node_v1_service_proto_rawDescGZIP(), []int{4}
}

type VoiceRelay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoiceRelay) Reset() {
	*x = VoiceRelay{}
	mi := &file_confa_node_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceRelay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceRelay) ProtoMessage() {}

func (x *VoiceRelay) ProtoReflect() protoreflect.Message {
	mi := &file_confa_node_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceRelay.ProtoReflect.Descriptor instead.
func (*VoiceRelay) Descriptor() ([]byte, []int) {
	return file_confa_node_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *VoiceRelay) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VoiceRelay) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VoiceRelay) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ListVoiceRelaysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoiceRelays   []*VoiceRelay          `protobuf:"bytes,1,rep,name=voice_relays,json=voiceRelays,proto3" json:"voice_relays,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVoiceRelaysResponse) Reset() {
	*x = ListVoiceRelaysResponse{}
	mi := &file_confa_node_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVoiceRelaysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVoiceRelaysResponse) ProtoMessage() {}

func (x *ListVoiceRelaysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_confa_node_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVoiceRelaysResponse.ProtoReflect.Descriptor instead.
func (*ListVoiceRelaysResponse) Descriptor() ([]byte, []int) {
	return file_confa_node_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListVoiceRelaysResponse) GetVoiceRelays() []*VoiceRelay {
	if x != nil {
		return x.VoiceRelays
	}
	return nil
}

type ListAuthProvidersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuthProvidersRequest) Reset() {
	*x = ListAuthProvidersRequest{}
	mi := &file_confa_node_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuthProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuthProvidersRequest) ProtoMessage() {}

func (x *ListAuthProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_confa_node_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuthProvidersRequest.ProtoReflect.Descriptor instead.
func (*ListAuthProvidersRequest) Descriptor() ([]byte, []int) {
	return file_confa_node_v1_service_proto_rawDescGZIP(), []int{7}
}

type ListAuthProvidersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthProviders []*AuthProvider        `protobuf:"bytes,1,rep,name=auth_providers,json=authProviders,proto3" json:"auth_providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuthProvidersResponse) Reset() {
	*x = ListAuthProvidersResponse{}
	mi := &file_confa_node_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuthProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuthProvidersResponse) ProtoMessage() {}

func (x *ListAuthProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_confa_node_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuthProvidersResponse.ProtoReflect.Descriptor instead.
func (*ListAuthProvidersResponse) Descriptor() ([]byte, []int) {
	return file_confa_node_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListAuthProvidersResponse) GetAuthProviders() []*AuthProvider {
	if x != nil {
		return x.AuthProviders
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_confa_node_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_confa_node_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_confa_node_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *v1.User               `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_confa_node_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_confa_node_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_confa_node_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserResponse) GetUser() *v1.User {
	if x != nil {
		return x.User
	}
	return nil
}

type CurrentUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentUserRequest) Reset() {
	*x = CurrentUserRequest{}
	mi := &file_confa_node_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentUserRequest) ProtoMessage() {}

func (x *CurrentUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_confa_node_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentUserRequest.ProtoReflect.Descriptor instead.
func (*CurrentUserRequest) Descriptor() ([]byte, []int) {
	return file_confa_node_v1_service_proto_rawDescGZIP(), []int{11}
}

type CurrentUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *v1.User               `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentUserResponse) Reset() {
	*x = CurrentUserResponse{}
	mi := &file_confa_node_v1_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentUserResponse) ProtoMessage() {}

func (x *CurrentUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_confa_node_v1_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentUserResponse.ProtoReflect.Descriptor instead.
func (*CurrentUserResponse) Descriptor() ([]byte, []int) {
	return file_confa_node_v1_service_proto_rawDescGZIP(), []int{12}
}

func (x *CurrentUserResponse) GetUser() *v1.User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_confa_node_v1_service_proto protoreflect.FileDescriptor

const file_confa_node_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1bconfa/node/v1/service.proto\x12\rconfa.node.v1\x1a!confa/node/v1/auth_provider.proto\x1a\x18confa/user/v1/user.proto\x1a\x16confa/extensions.proto\"I\n" +
	"\x1eSupportedClientVersionsRequest\x12'\n" +
	"\x0fcurrent_version\x18\x01 \x01(\tR\x0ecurrentVersion\"`\n" +
	"\x1fSupportedClientVersionsResponse\x12\x1c\n" +
	"\tsupported\x18\x01 \x01(\bR\tsupported\x12\x1f\n" +
	"\vmin_version\x18\x02 \x01(\tR\n" +
	"minVersion\"\x14\n" +
	"\x12ListServersRequest\"4\n" +
	"\x13ListServersResponse\x12\x1d\n" +
	"\n" +
	"server_ids\x18\x01 \x03(\tR\tserverIds\"\x18\n" +
	"\x16ListVoiceRelaysRequest\"J\n" +
	"\n" +
	"VoiceRelay\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"W\n" +
	"\x17ListVoiceRelaysResponse\x12<\n" +
	"\fvoice_relays\x18\x01 \x03(\v2\x19.confa.node.v1.VoiceRelayR\vvoiceRelays\"\x1a\n" +
	"\x18ListAuthProvidersRequest\"_\n" +
	"\x19ListAuthProvidersResponse\x12B\n" +
	"\x0eauth_providers\x18\x01 \x03(\v2\x1b.confa.node.v1.AuthProviderR\rauthProviders\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\":\n" +
	"\x0fGetUserResponse\x12'\n" +
	"\x04user\x18\x01 \x01(\v2\x13.confa.user.v1.UserR\x04user\"\x14\n" +
	"\x12CurrentUserRequest\">\n" +
	"\x13CurrentUserResponse\x12'\n" +
	"\x04user\x18\x01 \x01(\v2\x13.confa.user.v1.UserR\x04user2\xd5\x04\n" +
	"\vNodeService\x12~\n" +
	"\x17SupportedClientVersions\x12-.confa.node.v1.SupportedClientVersionsRequest\x1a..confa.node.v1.SupportedClientVersionsResponse\"\x04\xa8\xa1\x10\x01\x12l\n" +
	"\x11ListAuthProviders\x12'.confa.node.v1.ListAuthProvidersRequest\x1a(.confa.node.v1.ListAuthProvidersResponse\"\x04\xa8\xa1\x10\x01\x12H\n" +
	"\aGetUser\x12\x1d.confa.node.v1.GetUserRequest\x1a\x1e.confa.node.v1.GetUserResponse\x12T\n" +
	"\vCurrentUser\x12!.confa.node.v1.CurrentUserRequest\x1a\".confa.node.v1.CurrentUserResponse\x12V\n" +
	"\rListServerIDs\x12!.confa.node.v1.ListServersRequest\x1a\".confa.node.v1.ListServersResponse\x12`\n" +
	"\x0fListVoiceRelays\x12%.confa.node.v1.ListVoiceRelaysRequest\x1a&.confa.node.v1.ListVoiceRelaysResponseB\xb2\x01\n" +
	"\x11com.confa.node.v1B\fServiceProtoP\x01Z9github.com/confa-chat/node/src/proto/confa/node/v1;nodev1\xa2\x02\x03CNX\xaa\x02\rConfa.Node.V1\xca\x02\rConfa\\Node\\V1\xe2\x02\x19Confa\\Node\\V1\\GPBMetadata\xea\x02\x0fConfa::Node::V1b\x06proto3"

var (
	file_confa_node_v1_service_proto_rawDescOnce sync.Once
	file_confa_node_v1_service_proto_rawDescData []byte
)

func file_confa_node_v1_service_proto_rawDescGZIP() []byte {
	file_confa_node_v1_service_proto_rawDescOnce.Do(func() {
		file_confa_node_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_confa_node_v1_service_proto_rawDesc), len(file_confa_node_v1_service_proto_rawDesc)))
	})
	return file_confa_node_v1_service_proto_rawDescData
}

var file_confa_node_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_confa_node_v1_service_proto_goTypes = []any{
	(*SupportedClientVersionsRequest)(nil),  // 0: confa.node.v1.SupportedClientVersionsRequest
	(*SupportedClientVersionsResponse)(nil), // 1: confa.node.v1.SupportedClientVersionsResponse
	(*ListServersRequest)(nil),              // 2: confa.node.v1.ListServersRequest
	(*ListServersResponse)(nil),             // 3: confa.node.v1.ListServersResponse
	(*ListVoiceRelaysRequest)(nil),          // 4: confa.node.v1.ListVoiceRelaysRequest
	(*VoiceRelay)(nil),                      // 5: confa.node.v1.VoiceRelay
	(*ListVoiceRelaysResponse)(nil),         // 6: confa.node.v1.ListVoiceRelaysResponse
	(*ListAuthProvidersRequest)(nil),        // 7: confa.node.v1.ListAuthProvidersRequest
	(*ListAuthProvidersResponse)(nil),       // 8: confa.node.v1.ListAuthProvidersResponse
	(*GetUserRequest)(nil),                  // 9: confa.node.v1.GetUserRequest
	(*GetUserResponse)(nil),                 // 10: confa.node.v1.GetUserResponse
	(*CurrentUserRequest)(nil),              // 11: confa.node.v1.CurrentUserRequest
	(*CurrentUserResponse)(nil),             // 12: confa.node.v1.CurrentUserResponse
	(*AuthProvider)(nil),                    // 13: confa.node.v1.AuthProvider
	(*v1.User)(nil),                         // 14: confa.user.v1.User
}
var file_confa_node_v1_service_proto_depIdxs = []int32{
	5,  // 0: confa.node.v1.ListVoiceRelaysResponse.voice_relays:type_name -> confa.node.v1.VoiceRelay
	13, // 1: confa.node.v1.ListAuthProvidersResponse.auth_providers:type_name -> confa.node.v1.AuthProvider
	14, // 2: confa.node.v1.GetUserResponse.user:type_name -> confa.user.v1.User
	14, // 3: confa.node.v1.CurrentUserResponse.user:type_name -> confa.user.v1.User
	0,  // 4: confa.node.v1.NodeService.SupportedClientVersions:input_type -> confa.node.v1.SupportedClientVersionsRequest
	7,  // 5: confa.node.v1.NodeService.ListAuthProviders:input_type -> confa.node.v1.ListAuthProvidersRequest
	9,  // 6: confa.node.v1.NodeService.GetUser:input_type -> confa.node.v1.GetUserRequest
	11, // 7: confa.node.v1.NodeService.CurrentUser:input_type -> confa.node.v1.CurrentUserRequest
	2,  // 8: confa.node.v1.NodeService.ListServerIDs:input_type -> confa.node.v1.ListServersRequest
	4,  // 9: confa.node.v1.NodeService.ListVoiceRelays:input_type -> confa.node.v1.ListVoiceRelaysRequest
	1,  // 10: confa.node.v1.NodeService.SupportedClientVersions:output_type -> confa.node.v1.SupportedClientVersionsResponse
	8,  // 11: confa.node.v1.NodeService.ListAuthProviders:output_type -> confa.node.v1.ListAuthProvidersResponse
	10, // 12: confa.node.v1.NodeService.GetUser:output_type -> confa.node.v1.GetUserResponse
	12, // 13: confa.node.v1.NodeService.CurrentUser:output_type -> confa.node.v1.CurrentUserResponse
	3,  // 14: confa.node.v1.NodeService.ListServerIDs:output_type -> confa.node.v1.ListServersResponse
	6,  // 15: confa.node.v1.NodeService.ListVoiceRelays:output_type -> confa.node.v1.ListVoiceRelaysResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_confa_node_v1_service_proto_init() }
func file_confa_node_v1_service_proto_init() {
	if File_confa_node_v1_service_proto != nil {
		return
	}
	file_confa_node_v1_auth_provider_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_confa_node_v1_service_proto_rawDesc), len(file_confa_node_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_confa_node_v1_service_proto_goTypes,
		DependencyIndexes: file_confa_node_v1_service_proto_depIdxs,
		MessageInfos:      file_confa_node_v1_service_proto_msgTypes,
	}.Build()
	File_confa_node_v1_service_proto = out.File
	file_confa_node_v1_service_proto_goTypes = nil
	file_confa_node_v1_service_proto_depIdxs = nil
}
